/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package clases_sobre_figuras_geometricas;

/**
 *
 * @author Santi
 */
public class ventana_principal extends javax.swing.JFrame {

    /**
     * Creates new form ventana_principal
     */
    public ventana_principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txt_circulo_radio = new javax.swing.JTextField();
        txt_circulo_area = new javax.swing.JTextField();
        txt_circulo_perimetro = new javax.swing.JTextField();
        btn_circulo_area = new javax.swing.JButton();
        btn_circulo_perimetro = new javax.swing.JButton();
        btn_circulo_borrar = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        txt_cuadrado_lado = new javax.swing.JTextField();
        btn_cuadrado_area = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txt_cuadrado_area = new javax.swing.JTextField();
        txt_cuadrado_perimetro = new javax.swing.JTextField();
        btn_cuadrado_perimetro = new javax.swing.JButton();
        btn_cuadrado_borrar = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        txt_rectangulo_base = new javax.swing.JTextField();
        txt_rectangulo_altura = new javax.swing.JTextField();
        txt_rectangulo_area = new javax.swing.JTextField();
        txt_rectangulo_perimetro = new javax.swing.JTextField();
        btn_rectangulo_area = new javax.swing.JButton();
        btn_rectangulo_perimetro = new javax.swing.JButton();
        btn_rectangulo_borrar = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        txt_triangulo_base = new javax.swing.JTextField();
        txt_triangulo_altura = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        txt_triangulo_area = new javax.swing.JTextField();
        txt_triangulo_perimetro = new javax.swing.JTextField();
        btn_triangulo_area = new javax.swing.JButton();
        btn_triangulo_perimetro = new javax.swing.JButton();
        jLabel20 = new javax.swing.JLabel();
        txt_triangulo_tipo = new javax.swing.JTextField();
        btn_triangulo_tipo = new javax.swing.JButton();
        btn_triangulo_borrar = new javax.swing.JButton();
        jLabel21 = new javax.swing.JLabel();
        txt_triangulo_hipotenusa = new javax.swing.JTextField();
        btn_triangulo_hipotenusa = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Figuras geometricas");
        jLabel1.setRequestFocusEnabled(false);
        jLabel1.setVerifyInputWhenFocusTarget(false);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Circulo");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Cuadrado");

        jLabel4.setText("Radio");

        jLabel5.setText("Area");

        jLabel6.setText("Perimetro");

        btn_circulo_area.setText("Calcular area");
        btn_circulo_area.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_circulo_areaActionPerformed(evt);
            }
        });

        btn_circulo_perimetro.setText("Calcular perimetro");
        btn_circulo_perimetro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_circulo_perimetroActionPerformed(evt);
            }
        });

        btn_circulo_borrar.setText("Borrar");
        btn_circulo_borrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_circulo_borrarActionPerformed(evt);
            }
        });

        jLabel7.setText("Lado");

        btn_cuadrado_area.setText("Calcular area");
        btn_cuadrado_area.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cuadrado_areaActionPerformed(evt);
            }
        });

        jLabel8.setText("Area");

        jLabel9.setText("Perimetro");

        btn_cuadrado_perimetro.setText("Calcular perimetro");
        btn_cuadrado_perimetro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cuadrado_perimetroActionPerformed(evt);
            }
        });

        btn_cuadrado_borrar.setText("Borrar");
        btn_cuadrado_borrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cuadrado_borrarActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Rectangulo");

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Triangulo");

        jLabel12.setText("Base");

        jLabel13.setText("Altura");

        jLabel14.setText("Area");

        jLabel15.setText("Perimetro");

        txt_rectangulo_altura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_rectangulo_alturaActionPerformed(evt);
            }
        });

        btn_rectangulo_area.setText("Calcular area");
        btn_rectangulo_area.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_rectangulo_areaActionPerformed(evt);
            }
        });

        btn_rectangulo_perimetro.setText("Calcular perimetro");
        btn_rectangulo_perimetro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_rectangulo_perimetroActionPerformed(evt);
            }
        });

        btn_rectangulo_borrar.setText("Borrar");
        btn_rectangulo_borrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_rectangulo_borrarActionPerformed(evt);
            }
        });

        jLabel16.setText("Base");

        jLabel17.setText("Altura");

        txt_triangulo_altura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_triangulo_alturaActionPerformed(evt);
            }
        });

        jLabel18.setText("Area");

        jLabel19.setText("Perimetro");

        btn_triangulo_area.setText("Calcular area");
        btn_triangulo_area.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_triangulo_areaActionPerformed(evt);
            }
        });

        btn_triangulo_perimetro.setText("Calcular perimetro");
        btn_triangulo_perimetro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_triangulo_perimetroActionPerformed(evt);
            }
        });

        jLabel20.setText("Tipo");

        btn_triangulo_tipo.setText("Determinar tipo");
        btn_triangulo_tipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_triangulo_tipoActionPerformed(evt);
            }
        });

        btn_triangulo_borrar.setText("Borrar");
        btn_triangulo_borrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_triangulo_borrarActionPerformed(evt);
            }
        });

        jLabel21.setText("Hipotenusa");

        btn_triangulo_hipotenusa.setText("Calcular hipotenusa");
        btn_triangulo_hipotenusa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_triangulo_hipotenusaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btn_circulo_borrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txt_circulo_radio)
                            .addComponent(txt_circulo_area)
                            .addComponent(txt_circulo_perimetro, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btn_circulo_area, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn_circulo_perimetro, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(450, 450, 450)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txt_rectangulo_altura))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txt_rectangulo_base, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txt_rectangulo_area))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txt_rectangulo_perimetro)
                                    .addComponent(btn_rectangulo_borrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn_rectangulo_area, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_rectangulo_perimetro, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btn_cuadrado_borrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txt_cuadrado_area)
                            .addComponent(txt_cuadrado_perimetro)
                            .addComponent(txt_cuadrado_lado, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn_cuadrado_perimetro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn_cuadrado_area, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btn_triangulo_borrar, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                            .addComponent(txt_triangulo_tipo))
                        .addGap(18, 18, 18)
                        .addComponent(btn_triangulo_tipo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txt_triangulo_hipotenusa))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(txt_triangulo_area))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(txt_triangulo_altura))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(txt_triangulo_base, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(txt_triangulo_perimetro, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btn_triangulo_area, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn_triangulo_perimetro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn_triangulo_hipotenusa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(40, 40, 40))
            .addGroup(layout.createSequentialGroup()
                .addGap(140, 140, 140)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(170, 170, 170))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txt_circulo_radio, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txt_cuadrado_lado))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_circulo_area, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txt_circulo_area)
                    .addComponent(btn_cuadrado_area, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txt_cuadrado_area))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btn_cuadrado_perimetro, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                    .addComponent(txt_cuadrado_perimetro)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_circulo_perimetro, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txt_circulo_perimetro, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_cuadrado_borrar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_circulo_borrar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(100, 100, 100)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_rectangulo_base, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txt_rectangulo_altura)
                            .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txt_rectangulo_area)
                                .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE))
                            .addComponent(btn_rectangulo_area, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txt_rectangulo_perimetro)
                                .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE))
                            .addComponent(btn_rectangulo_perimetro, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_rectangulo_borrar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_triangulo_base, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txt_triangulo_altura)
                            .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btn_triangulo_area, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_triangulo_area))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btn_triangulo_perimetro, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_triangulo_perimetro))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel21, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txt_triangulo_hipotenusa)
                            .addComponent(btn_triangulo_hipotenusa, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(txt_triangulo_tipo)
                        .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btn_triangulo_tipo, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_triangulo_borrar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(64, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_rectangulo_alturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_rectangulo_alturaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_rectangulo_alturaActionPerformed

    private void txt_triangulo_alturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_triangulo_alturaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_triangulo_alturaActionPerformed

    private void btn_circulo_areaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_circulo_areaActionPerformed
        int radio;
        radio = Integer.parseInt(txt_circulo_radio.getText());
        circulo figura_circulo = new circulo(radio);
        double area_circulo = figura_circulo.calcular_area();
        txt_circulo_area.setText(String.valueOf(area_circulo));
    }//GEN-LAST:event_btn_circulo_areaActionPerformed

    private void btn_circulo_perimetroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_circulo_perimetroActionPerformed
        int radio;
        radio = Integer.parseInt(txt_circulo_radio.getText());
        circulo figura_circulo = new circulo(radio);
        double perimetro_circulo = figura_circulo.calcular_perimetro();
        txt_circulo_perimetro.setText(String.valueOf(perimetro_circulo));
    }//GEN-LAST:event_btn_circulo_perimetroActionPerformed

    private void btn_circulo_borrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_circulo_borrarActionPerformed
        txt_circulo_radio.setText("");
        txt_circulo_area.setText("");
        txt_circulo_perimetro.setText("");
    }//GEN-LAST:event_btn_circulo_borrarActionPerformed

    private void btn_cuadrado_areaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cuadrado_areaActionPerformed
        int lado;
        lado = Integer.parseInt(txt_cuadrado_lado.getText());
        cuadrado figura_cuadrado = new cuadrado(lado);
        double area_cuadrado = figura_cuadrado.calcular_area();
        txt_cuadrado_area.setText(String.valueOf(area_cuadrado));
    }//GEN-LAST:event_btn_cuadrado_areaActionPerformed

    private void btn_cuadrado_perimetroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cuadrado_perimetroActionPerformed
        int lado;
        lado = Integer.parseInt(txt_cuadrado_lado.getText());
        cuadrado figura_cuadrado = new cuadrado(lado);
        double perimetro_cuadrado = figura_cuadrado.calcular_perimetro();
        txt_cuadrado_perimetro.setText(String.valueOf(perimetro_cuadrado));
    }//GEN-LAST:event_btn_cuadrado_perimetroActionPerformed

    private void btn_cuadrado_borrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cuadrado_borrarActionPerformed
        txt_cuadrado_lado.setText("");
        txt_cuadrado_area.setText("");
        txt_cuadrado_perimetro.setText("");
    }//GEN-LAST:event_btn_cuadrado_borrarActionPerformed

    private void btn_rectangulo_areaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_rectangulo_areaActionPerformed
        int altura,base;
        base = Integer.parseInt(txt_rectangulo_base.getText());
        altura = Integer.parseInt(txt_rectangulo_altura.getText());
        rectangulo figura_rectangulo = new rectangulo(base,altura);
        double area_rectangulo = figura_rectangulo.calcular_area();
        txt_rectangulo_area.setText(String.valueOf(area_rectangulo));
    }//GEN-LAST:event_btn_rectangulo_areaActionPerformed

    private void btn_rectangulo_perimetroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_rectangulo_perimetroActionPerformed
        int altura,base;
        base = Integer.parseInt(txt_rectangulo_base.getText());
        altura = Integer.parseInt(txt_rectangulo_altura.getText());
        rectangulo figura_rectangulo = new rectangulo(base,altura);
        double perimetro_rectangulo = figura_rectangulo.calcular_perimetro();
        txt_rectangulo_perimetro.setText(String.valueOf(perimetro_rectangulo));
    }//GEN-LAST:event_btn_rectangulo_perimetroActionPerformed

    private void btn_rectangulo_borrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_rectangulo_borrarActionPerformed
        txt_rectangulo_base.setText("");
        txt_rectangulo_altura.setText("");
        txt_rectangulo_area.setText("");
        txt_rectangulo_perimetro.setText("");
    }//GEN-LAST:event_btn_rectangulo_borrarActionPerformed

    private void btn_triangulo_areaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_triangulo_areaActionPerformed
        int altura,base;
        base = Integer.parseInt(txt_triangulo_base.getText());
        altura = Integer.parseInt(txt_triangulo_altura.getText());
        triangulo_rectangulo figura_triangulo = new triangulo_rectangulo(base,altura);
        double area_triangulo = figura_triangulo.calcular_area();
        txt_triangulo_area.setText(String.valueOf(area_triangulo));
    }//GEN-LAST:event_btn_triangulo_areaActionPerformed

    private void btn_triangulo_perimetroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_triangulo_perimetroActionPerformed
        int altura,base;
        base = Integer.parseInt(txt_triangulo_base.getText());
        altura = Integer.parseInt(txt_triangulo_altura.getText());
        triangulo_rectangulo figura_triangulo = new triangulo_rectangulo(base,altura);
        double perimetro_triangulo = figura_triangulo.calcular_perimetro();
        txt_triangulo_perimetro.setText(String.valueOf(perimetro_triangulo));
    }//GEN-LAST:event_btn_triangulo_perimetroActionPerformed

    private void btn_triangulo_hipotenusaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_triangulo_hipotenusaActionPerformed
        int altura,base;
        base = Integer.parseInt(txt_triangulo_base.getText());
        altura = Integer.parseInt(txt_triangulo_altura.getText());
        triangulo_rectangulo figura_triangulo = new triangulo_rectangulo(base,altura);
        double hipotenusa_triangulo = figura_triangulo.calcular_hipotenusa();
        txt_triangulo_hipotenusa.setText(String.valueOf(hipotenusa_triangulo));
    }//GEN-LAST:event_btn_triangulo_hipotenusaActionPerformed

    private void btn_triangulo_tipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_triangulo_tipoActionPerformed
        int altura,base;
        base = Integer.parseInt(txt_triangulo_base.getText());
        altura = Integer.parseInt(txt_triangulo_altura.getText());
        triangulo_rectangulo figura_triangulo = new triangulo_rectangulo(base,altura);
        String tipo_triangulo = figura_triangulo.determinar_tipo();
        txt_triangulo_tipo.setText(tipo_triangulo);
    }//GEN-LAST:event_btn_triangulo_tipoActionPerformed

    private void btn_triangulo_borrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_triangulo_borrarActionPerformed
        txt_triangulo_base.setText("");
        txt_triangulo_altura.setText("");
        txt_triangulo_area.setText("");
        txt_triangulo_perimetro.setText("");
        txt_triangulo_hipotenusa.setText("");
        txt_triangulo_tipo.setText("");
    }//GEN-LAST:event_btn_triangulo_borrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ventana_principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ventana_principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ventana_principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ventana_principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ventana_principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_circulo_area;
    private javax.swing.JButton btn_circulo_borrar;
    private javax.swing.JButton btn_circulo_perimetro;
    private javax.swing.JButton btn_cuadrado_area;
    private javax.swing.JButton btn_cuadrado_borrar;
    private javax.swing.JButton btn_cuadrado_perimetro;
    private javax.swing.JButton btn_rectangulo_area;
    private javax.swing.JButton btn_rectangulo_borrar;
    private javax.swing.JButton btn_rectangulo_perimetro;
    private javax.swing.JButton btn_triangulo_area;
    private javax.swing.JButton btn_triangulo_borrar;
    private javax.swing.JButton btn_triangulo_hipotenusa;
    private javax.swing.JButton btn_triangulo_perimetro;
    private javax.swing.JButton btn_triangulo_tipo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField txt_circulo_area;
    private javax.swing.JTextField txt_circulo_perimetro;
    private javax.swing.JTextField txt_circulo_radio;
    private javax.swing.JTextField txt_cuadrado_area;
    private javax.swing.JTextField txt_cuadrado_lado;
    private javax.swing.JTextField txt_cuadrado_perimetro;
    private javax.swing.JTextField txt_rectangulo_altura;
    private javax.swing.JTextField txt_rectangulo_area;
    private javax.swing.JTextField txt_rectangulo_base;
    private javax.swing.JTextField txt_rectangulo_perimetro;
    private javax.swing.JTextField txt_triangulo_altura;
    private javax.swing.JTextField txt_triangulo_area;
    private javax.swing.JTextField txt_triangulo_base;
    private javax.swing.JTextField txt_triangulo_hipotenusa;
    private javax.swing.JTextField txt_triangulo_perimetro;
    private javax.swing.JTextField txt_triangulo_tipo;
    // End of variables declaration//GEN-END:variables
}
